const cars = [
  {
    id: "1",
    car_model: "Accord",
    brand: "honda",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "saloon",
    release_year: 2019,
    price_per_hour: 15,
    location: 'yangon',
    isReady: true
  },
  {
    id: "2",
    car_model: "Civic",
    brand: "honda",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "sedan",
    release_year: 2020,
    price_per_hour: 20,
    location: 'yangon',
    isReady: true
  },
  {
    id: "3",
    car_model: "Camry",
    brand: "toyota",
    people_capacity: 5,
    luggage_capacity: 3,
    doors: 4,
    car_type: "saloon",
    release_year: 2021,
    price_per_hour: 18,
    location: 'yangon',
    isReady: true
  },
  {
    id: "4",
    car_model: "Corolla",
    brand: "toyota",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "sedan",
    release_year: 2020,
    price_per_hour: 16,
    location: 'yangon',
    isReady: true
  },
  {
    id: "5",
    car_model: "3 Series",
    brand: "bmw",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "saloon",
    release_year: 2021,
    price_per_hour: 25,
    location: 'yangon',
    isReady: true
  },
  {
    id: "6",
    car_model: "A4",
    brand: "audi",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "sedan",
    release_year: 2022,
    price_per_hour: 22,
    location: 'yangon',
    isReady: true
  },
  {
    id: "7",
    car_model: "Fusion",
    brand: "ford",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "sedan",
    release_year: 2020,
    price_per_hour: 17,
    location: 'yangon',
    isReady: true
  },
  {
    id: "8",
    car_model: "Sonata",
    brand: "hyundai",
    people_capacity: 5,
    luggage_capacity: 3,
    doors: 4,
    car_type: "saloon",
    release_year: 2021,
    price_per_hour: 19,
    location: 'yangon',
    isReady: true
  },
  {
    id: "9",
    car_model: "Sonata",
    brand: "hyundai",
    people_capacity: 5,
    luggage_capacity: 3,
    doors: 4,
    car_type: "saloon",
    release_year: 2021,
    price_per_hour: 19,
    location: 'yangon',
    isReady: true
  },
  {
    id: "10",
    car_model: "Model 3",
    brand: "hyundai",
    people_capacity: 5,
    luggage_capacity: 2,
    doors: 4,
    car_type: "saloon",
    release_year: 2022,
    price_per_hour: 30,
    location: 'yangon',
    isReady: true
  },
  {
    id: "11",
    car_model: "Sonata",
    brand: "hyundai",
    people_capacity: 5,
    luggage_capacity: 3,
    doors: 4,
    car_type: "saloon",
    release_year: 2021,
    price_per_hour: 19,
    location: 'yangon',
    isReady: true
  },
  {
    id: "12",
    car_model: "S-Class",
    brand: "mercedes",
    people_capacity: 4,
    luggage_capacity: 2,
    doors: 4,
    car_type: "sedan",
    release_year: 2022,
    price_per_hour: 30,
    location: 'yangon',
    isReady: true
  },
];

export { cars };