let carList = [
    {
        "id": "car001",
        "car_model": "Accord",
        "brand": "honda",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2019,
        "price_per_hour": 15,
        "location": "Yangon",
        'isAutomatic': true
    },
    {
        "id": "car002",
        "car_model": "Civic",
        "brand": "honda",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2020,
        "price_per_hour": 20,
        "location": "Mandalay",
        'isAutomatic': true
    },
    {
        "id": "car003",
        "car_model": "Camry",
        "brand": "toyota",
        "people_capacity": 5,
        "luggage_capacity": 3,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2021,
        "price_per_hour": 18,
        "location": "Naypyidaw",
        'isAutomatic': true
    },
    {
        "id": "car004",
        "car_model": "Corolla",
        "brand": "toyota",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2020,
        "price_per_hour": 16,
        "location": "Bago",
        'isAutomatic': true
    },
    {
        "id": "car005",
        "car_model": "3 Series",
        "brand": "bmw",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2021,
        "price_per_hour": 25,
        "location": "Yangon",
        'isAutomatic': true
    },
    {
        "id": "car006",
        "car_model": "A4",
        "brand": "audi",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2022,
        "price_per_hour": 22,
        "location": "Mandalay",
        'isAutomatic': true
    },
    {
        "id": "car007",
        "car_model": "Fusion",
        "brand": "ford",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2020,
        "price_per_hour": 17,
        "location": "Naypyidaw",
        'isAutomatic': true
    },
    {
        "id": "car008",
        "car_model": "Sonata",
        "brand": "hyundai",
        "people_capacity": 5,
        "luggage_capacity": 3,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2021,
        "price_per_hour": 19,
        "location": "Bago",
        'isAutomatic': true
    },
    {
        "id": "car009",
        "car_model": "Sonata",
        "brand": "hyundai",
        "people_capacity": 5,
        "luggage_capacity": 3,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2021,
        "price_per_hour": 19,
        "location": "Yangon",
        'isAutomatic': true
    },
    {
        "id": "car010",
        "car_model": "Model 3",
        "brand": "hyundai",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2022,
        "price_per_hour": 30,
        "location": "Mandalay",
        'isAutomatic': true
    },
    {
        "id": "car011",
        "car_model": "Sonata",
        "brand": "hyundai",
        "people_capacity": 5,
        "luggage_capacity": 3,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2021,
        "price_per_hour": 19,
        "location": "Naypyidaw",
        'isAutomatic': true
    },
    {
        "id": "car012",
        "car_model": "S-Class",
        "brand": "mercedes",
        "people_capacity": 4,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2022,
        "price_per_hour": 30,
        "location": "Bago",
        'isAutomatic': true
    },
    {
        "id": "car013",
        "car_model": "Polo",
        "brand": "volkswagen",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2021,
        "price_per_hour": 18,
        "location": "Yangon",
        'isAutomatic': true
    },
    {
        "id": "car014",
        "car_model": "Model S",
        "brand": "tesla",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2022,
        "price_per_hour": 28,
        "location": "Mandalay",
        'isAutomatic': true
    },
    {
        "id": "car015",
        "car_model": "C-Class",
        "brand": "mercedes",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "saloon",
        "release_year": 2020,
        "price_per_hour": 24,
        "location": "Naypyidaw",
        'isAutomatic': true
    },
    {
        "id": "car016",
        "car_model": "Mazda3",
        "brand": "mazda",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2021,
        "price_per_hour": 16,
        "location": "Bago",
        'isAutomatic': true
    },
    {
        "id": "car017",
        "car_model": "Fiesta",
        "brand": "ford",
        "people_capacity": 5,
        "luggage_capacity": 2,
        "doors": 4,
        "car_type": "sedan",
        "release_year": 2020,
        "price_per_hour": 16,
        "location": "Bago",
        'isAutomatic': true
    }
];

export { carList };